repos:
  - repo: https://github.com/ambv/black
    rev: "22.10.0"
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: "v3.9.0"
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies: [
          flake8-bugbear,
        ]
